### ISSUE TITLE
How to load it ?

### ISSUE THREAD

**Issue by feldti** [Yesplan/Json-WebToken#2]
I have such a simple question: how do I load this library into Gemstone/S ?

**Comment by feldti** [comment]
Ok, I tried loading

**Comment by feldti** [comment]
Ok, I tried loadingit via

Metacello new
  repository: 'github://Yesplan/Json-WebToken:main/repository';
  baseline: 'JsonWebToken';
  load

but got the following error:

a MetacelloConflictingProjectError occurred (error 2710), Load Conflict between existing BaselineOfPharoCompatibility [baseline] from github://glassdb/PharoCompatibility:master/repository and BaselineOfPharoCompatibility [baseline] from github://GsDevKit/PharoCompatibility:master/repository

**Comment by jbrichau** [comment]
Sorry for missing this issue from almost 2 years ago. I had issues with notifications from github a while back, probably because of that.

You need to solve such load conflicts with the Metacello API. In this case, you seem to already have loaded the BaselineOfPharoCompatibility from glassdb github project, but that project was replaced with the one in the GsDevKit github project. So, you can safely make Metacello use the one from GsDevKit.

If you have any question, please drop me a not via the GLASS mailinglist: https://lists.gemtalksystems.com/mailman/listinfo/glass
